version: '3'
services:
  express:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/express
    depends_on:
      - db
      - seed
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/FEC
    command: sh -c 'until nc -z db 5432; do sleep 1; done; npm start'

  db:
    image: postgres:latest
    restart: always
    environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: password
       POSTGRES_DB: FEC
       PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8080:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=password
      - PGADMIN_LISTEN_PORT=80
      - PGADMIN_SKIP_NATIVE_AUTH=true

  seed:
    build: .
    volumes:
        - ./db:/app/db
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/FEC
    command: sh -c 'until nc -z db 5432; do sleep 1; done'

volumes:
    db-data:
